

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17   # 使用 LTS 版本（推荐生产环境）
    container_name: jenkins
    restart: always
    privileged: true                   # 避免容器内权限问题（可选）
    user: root                         # 以 root 用户运行（可选，解决挂载目录权限问题）
    ports:
      - "8080:8080"                    # Web 访问端口
      - "50000:50000"                  # Jenkins Agent 通信端口
    volumes:
      - ./jenkins_home:/var/jenkins_home   # 持久化 Jenkins 配置和数据
      - /var/run/docker.sock:/var/run/docker.sock  # 允许 Jenkins 调用宿主机 Docker（可选）
    environment:
      - TZ=Asia/Shanghai
      #- JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # 跳过初始化向导（可选）
    # 指定了容器启动时要执行的主命令
    entrypoint: >
      sh -c "
      apt-get update &&
      apt-get install -y docker.io &&
      exec /usr/local/bin/jenkins.sh
      "