services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    sysctls:
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.default.forwarding: 1
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - ./ovpn-data:/etc/openvpn
    environment:
      - TZ=Asia/Shanghai