global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  receiver: 'teams-webhook'
  routes:
    - match:
        severity: critical
      receiver: 'teams-webhook'

receivers:
  - name: 'teams-webhook'
    webhook_configs:
      - url: 'http://prometheus-msteams:2000/alertmanager'
        send_resolved: true
