global:
  smtp_smarthost: "smtp.163.com:465"              # 配置SMTP服务器和端口
  smtp_from: "18351585965@163.com"                 # 发件人邮箱
  smtp_auth_username: "18351585965@163.com"        # 登录邮箱用户名
  smtp_auth_password: "JAbpqatUhGiFBuL2"           # 登录密码或授权码
  smtp_require_tls: false                          # 使用SSL时设为false 
  smtp_tls_config:
    insecure_skip_verify: false  # 如果证书无效且你信任它，可以临时改为 true

route:
  receiver: "email"
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: "email"
    email_configs:
      - to: "panpan.xue@centific.com"
        send_resolved: true                         # 发送恢复通知
        headers:
          Subject: "Prometheus Alert - {{ .Status }}" # 自定义邮件主题

   