
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 159a357B!@
      MYSQL_DATABASE: mydata
      MYSQL_USER: xpp
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mysql_network

#volumes:
  #mysql_data:

networks:
  mysql_network:
