# Stage 1: Build PHP-FPM
FROM php:7.4-fpm AS php-fpm

USER root
WORKDIR /src/

# Install dependencies
RUN apt-get update -y && \
    apt-get install -y build-essential locales zip procps exiftool openssl pkg-config busybox net-tools && \
    apt-get install -y jpegoptim optipng pngquant gifsicle vim unzip git curl \
    libonig-dev libzip-dev libcurl4-openssl-dev libwebp-dev libjpeg62-turbo-dev \
    libpng-dev libxpm-dev libfreetype6-dev libldap2-dev && \
    pecl install -o -f redis

# Install PHP extensions
RUN docker-php-ext-install mysqli mbstring zip exif pcntl curl pdo_mysql ldap

# Configure GD
RUN docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Enable Redis extension
RUN echo "extension=redis.so" > /usr/local/etc/php/conf.d/docker-php-ext-redis.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

# Copy configuration
COPY config/php.ini /usr/local/etc/php/php.ini
COPY config/www.conf /usr/local/etc/php-fpm.d/www.conf


# Stage 2: Build Nginx
FROM nginx:alpine AS nginx

# Install openrc and vim
RUN apk add openrc vim --no-cache

# Copy configuration
COPY config/nginx.conf /etc/nginx/nginx.conf
COPY config/conf.d/my.oneforma.com.conf /etc/nginx/conf.d
COPY config/ssl /etc/nginx/ssl
COPY PactformaID /var/www

# Set environment variable
ENV ENV="/etc/environment"

# Copy PHP-FPM
COPY --from=php-fpm /usr/local/bin/php /usr/local/bin/php
COPY --from=php-fpm /usr/local/bin/composer /usr/local/bin/composer
COPY --from=php-fpm /usr/local/etc/php /usr/local/etc/php

# Expose ports
EXPOSE 80 443

# Run both services using Supervisor
RUN apk add --no-cache supervisor
COPY config/supervisord.conf /etc/supervisord.conf
CMD ["supervisord", "-c", "/etc/supervisord.conf"]
